CREATE TABLE `levels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `custom_song_id` INT(11) NULL,
  `official_song_id` INT(11) NULL,
  `version` SMALLINT(5) UNSIGNED NOT NULL,
  `length` TINYINT(1) NOT NULL,
  `two_player` TINYINT(1) NOT NULL,
  `publicity` TINYINT(1) NOT NULL,
  `render_str` VARCHAR(256) NOT NULL,
  `game_version` TINYINT(3) UNSIGNED NOT NULL,
  `binary_version` TINYINT(3) UNSIGNED NOT NULL,
  `upload_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `original_id` INT(11) NULL,
  `downloads` INT(11) UNSIGNED NOT NULL,
  `likes` INT(11) NOT NULL,
  `stars` TINYINT(2) UNSIGNED NOT NULL,
  `difficulty` TINYINT(3) UNSIGNED NOT NULL,
  `demon_difficulty` TINYINT(1) UNSIGNED NOT NULL,
  `coins` TINYINT(2) UNSIGNED NOT NULL,
  `coins_verified` TINYINT(1) NOT NULL,
  `requested_stars` TINYINT(2) UNSIGNED NOT NULL,
  `feature_order` INT(11) NOT NULL,
  `search_flags` SMALLINT UNSIGNED NOT NULL,
  `low_detail_mode` TINYINT(1) NOT NULL,
  `object_count` SMALLINT UNSIGNED NOT NULL,
  `copy_password` INT(8) NOT NULL,
  `building_time` INT NOT NULL,
  `update_locked` TINYINT(1) NOT NULL,
  `deleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE = InnoDB;
